### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by climb-yang** [microsoft/Spartan#35]
**Spartan offers the fastest prover with speedups of 36–152× depending on the baseline, produces proofs that are shorter by 1.2–416×。**

Does it mean that the size of the proofs shorter by 1.2-416x? 
If not, this means the time to generate the proof of generation shorter by 1.2x . 36x speedups of prover,  but only with 1.2x shorter produces proofs , why the difference so big?

**Comment by srinathsetty** [comment]
There is no (direct) relationship between prover time speedups and proof size reductions. Spartan's prover is faster than baselines because its underlying algorithms are fast (e.g., the sum-check protocol) and also because it avoids certain superlinear algorithms used in other proof systems (e.g., FFT). Our paper (https://eprint.iacr.org/2019/550.pdf) provides more details.
